applcation/config/routes.rb
Rails.application.routes.draw do
  resources :dash_boards
  resources :employees
  resources :books
 devise_for :users, controllers: { sessions: 'users/sessions' } # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 get 'search_employees' => 'employees#search_employee'
 get 'users/signout' 
 get 'load_link_details' => 'dash_boards#load_link_details'
 get 'check_link_details' => 'dash_boards#check_link_details' 
 get 'check_employee_type' => 'employees#check_employee_type'
 get 'organization_chart' => 'dash_boards#show_organization_chart'
 get 'emp_list_show' => 'employees#emp_list_show'
 get 'employeelogincreate' => 'employees#login_page'
 post 'employees/create_credentials' =>'employees#create_credentials'
# get 'search_employees' => 'employees#search_employee'
 root to: "dash_boards#index"
get 'dep_create'=>'departments#new'
 post 'departments/create' => 'departments#create'
end

applcation/app/models/department.rb
class Department < ApplicationRecord
has_many :designations
  
  validates :dep_code, presence: true, uniqueness: true
  
  validates :dep_name, presence: true, uniqueness: true
end

applcation/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
def new
@department = Department.new
@designation = Designation.new
if params[:from] != 'same'

	render :layout => false

end
end

def create
status = false
if (Department.exists?(dep_name: params[:department][:dep_name]) || Department.exists?(dep_code: params[:department][:dep_code]) )
@department = Department.where(params_require).first
if @department.blank?
@department = Department.create(params_require)
end
else
@department  = Department.new(params_require)
status = @department.save
end
if !@department.blank?
@designation = @department.designations.new(:name => params[:designation])
if !@designation.department_id.blank?
status =@designation.save
end
end
if status
flash[:notice]="succesfull"
redirect_to :action => 'new', :local => @department, :from=> 'same'

else
flash[:notice] = "unsuccess"
render :action => 'new', :local => @department, :from=> 'same'

end

end

private

def params_require
params.require(:department).permit(:dep_name, :dep_code)

end
end

applcation/app/helpers/departments_helper.rb
module DepartmentsHelper
end

applcation/app/views/departments/department_creation.html.erb
<p id="notice"><%= notice %></p>


<%= form_for(:department_create, local: true , url: departments_create_path) do |form| %>

  <% if @depart.errors.any? %>
<ul>
  <% @depart.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<table><tr>
  <div class="field">
     <td width='30%'><%= form.label :'Department Name' %></td>
    <td><%= form.text_field :department_name %></td>
  </div>
</tr>
<tr>
  <div class="field">
     <td width='30%'><%= form.label :'Department Code' %></td>
    <td><%= form.text_field :department_code %></td>
  </div>
</tr>
<tr>
  <div class="field">
     <td width='30%'><%= form.label :'Designation' %></td>
    <td><%= form.text_field :designation %></td>
  </div>
</tr>
<tr>
  <td colspan = "2">
  <div class="actions" id ="action">
    <center><%= form.submit %></center>
  </div>
</td>
</tr>
</table>

<%end%>

applcation/app/views/departments/new.html.erb
<h2>Department Creation</h2>
<%= form_tag departments_create_path do |f| %>
<% if @department.errors.any? %>
<ul>
  <% @department.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<p id="notice"><%= notice %></p>

<%end%>

<% if @designation.errors.any? %>
<ul>
  <% @designation.errors.full_messages.each do |msg| %>
    <li><%= 'Designation' + msg.to_s %></li>
  <% end %>
</ul>
<%end%>
<table><tr>
  <div class="field">
     <td width='30%'><%= 'Department Name:' %></td>
    <td><%= text_field_tag :'department[dep_name]' %></td>  
  </div>
</tr>
<tr>
  <div class="field">
     <td width='30%'><%= "Department Code:" %></td>
    <td><%= text_field_tag :'department[dep_code]' %></td> 
  </div>
</tr>
<tr>
  <div class="field">
     <td width='30%'><%= 'Designation:' %></td>
    <td><%= text_field_tag :designation %></td> 
  </div>
</tr>
<tr>
  <td colspan = "2">
  <div class="actions" id ="action"> 
  
    <center><%= submit_tag :save, :id=> 'login_emp', style: 'width:40%;background-color:#0066A2;color:white;    border-radius: 10px 10px 10px 10px;border-style: outset;' %></center>
  </div>
</td>
</tr>
</table>

<%end%>