applcation/config/routes.rb
Rails.application.routes.draw do
  resources :dash_boards
  resources :employees
  resources :books
 devise_for :users, controllers: { sessions: 'users/sessions' } # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 get 'search_employees' => 'employees#search_employee'
 get 'users/signout' 
 get 'load_link_details' => 'dash_boards#load_link_details'
 get 'check_link_details' => 'dash_boards#check_link_details' 
 get 'check_employee_type' => 'employees#check_employee_type'
 get 'organization_chart' => 'dash_boards#show_organization_chart'
 get 'emp_list_show' => 'employees#emp_list_show'
 get 'employeelogincreate' => 'employees#login_page'
 post 'employees/create_credentials' =>'employees#create_credentials'
# get 'search_employees' => 'employees#search_employee'
 root to: "dash_boards#index"
get 'dep_create'=>'departments#new'
 post 'departments/create' => 'departments#create'
end

applcation/app/models/dash_board.rb
class DashBoard < ApplicationRecord
	has_many :link_details

end

applcation/app/controllers/dash_boards_controller.rb
class DashBoardsController < ApplicationController
  before_action :set_dash_board, only: [:show, :edit, :update, :destroy]

  # GET /dash_boards
  # GET /dash_boards.json
  def index
    @dash_boards = DashBoard.all
  end

  # GET /dash_boards/1
  # GET /dash_boards/1.json
  def show
  end

  # GET /dash_boards/new
  def new
    @dash_board = DashBoard.new
  end

  # GET /dash_boards/1/edit
  def edit
  end
 def check_link_details
  @details = DashBoard.find_by_link_name(params[:name]).link_details
   
 render json: { "stat": @details.present? } 

  end
  def load_link_details
 @link_details = DashBoard.find_by_link_name(params[:name]).link_details
 render :layout => false
  end
  # POST /dash_boards
  # POST /dash_boards.json
  def create
    @dash_board = DashBoard.new(dash_board_params)

    respond_to do |format|
      if @dash_board.save
        format.html { redirect_to @dash_board, notice: 'Dash board was successfully created.' }
        format.json { render :show, status: :created, location: @dash_board }
      else
        format.html { render :new }
        format.json { render json: @dash_board.errors, status: :unprocessable_entity }
      end
    end
  end

def show_organization_chart
@ceo_emp = Employee.where("level =?" ,  "CEO")
render :layout => false
end

  # PATCH/PUT /dash_boards/1
  # PATCH/PUT /dash_boards/1.json
  def update
    respond_to do |format|
      if @dash_board.update(dash_board_params)
        format.html { redirect_to @dash_board, notice: 'Dash board was successfully updated.' }
        format.json { render :show, status: :ok, location: @dash_board }
      else
        format.html { render :edit }
        format.json { render json: @dash_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dash_boards/1
  # DELETE /dash_boards/1.json
  def destroy
    @dash_board.destroy
    respond_to do |format|
      format.html { redirect_to dash_boards_url, notice: 'Dash board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dash_board
      @dash_board = DashBoard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dash_board_params
      params.fetch(:dash_board, {})
    end
end

applcation/app/helpers/dash_boards_helper.rb
module DashBoardsHelper
end

applcation/app/views/dash_boards/_form.html.erb
<%= form_with(model: dash_board, local: true) do |form| %>
  <% if dash_board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dash_board.errors.count, "error") %> prohibited this dash_board from being saved:</h2>

      <ul>
      <% dash_board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

applcation/app/views/dash_boards/edit.html.erb
<h1>Editing Dash Board</h1>

<%= render 'form', dash_board: @dash_board %>

<%= link_to 'Show', @dash_board %> |
<%= link_to 'Back', dash_boards_path %>

applcation/app/views/dash_boards/index.html.erb
<% if !notice.blank?%>
  <p  class ="alert" bg-color="red"><%= notice %></p>
       <%end%>
<div align='left'>

<table>
  
  <td id = 'new_employee'>
    <h1>Dash Boards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dash_boards.each do |dash_board| %>
      <tr>
        <td><%= link_to 'Show', dash_board %></td>
        <td><%= link_to 'Edit', edit_dash_board_path(dash_board) %></td>
        <td><%= link_to 'Destroy', dash_board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dash Board', new_dash_board_path %>


  </td>
</table>
</div>

applcation/app/views/dash_boards/load_link_details.html.erb
<%for detail in @link_details%>

<div style="background-color:  #BDB76B ; border-color: green; border-radius: 3px;"><b><a id = 'det_links', href= "javascript:checkDetail('<%=detail.url_path %>');"><font color="White" size="3"><%=detail.detail_name%></font></a></b><hr /></div>



<%end%>

applcation/app/views/dash_boards/new.html.erb
<h1>New Dash Board</h1>

<%= render 'form', dash_board: @dash_board %>

<%= link_to 'Back', dash_boards_path %>

applcation/app/views/dash_boards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dash_board_path(@dash_board) %> |
<%= link_to 'Back', dash_boards_path %>

applcation/app/views/dash_boards/show_organization_chart.html.erb
<style>
.blue{

    display: inline-block;
  font-family: 'Gabriela', serif;
  color: #b78726;
  font-size: 1.3em;
  border-radius: 5px;
  background: #e8bbe2; /* alpha value for background */
  

}
.level{
  display: inline-block;
  font-family: 'Gabriela', serif;
  color: #b78726;
  font-size: 1.0em;
  border-radius: 5px;
  background: #c6efef;


}
.high{
  display: inline-block;
  border-radius: 5px;
  font-size: 1.8em;

background-color: #e5e3e3;


}
</style>

<div class="col-sm-4"  style="background-color: #e5e3e3;    outline: 1px solid lightgray;">
<%for emp in @ceo_emp%>
 
<%manager =  emp.subordinates%>
<% count1 = manager.size%>
<%if !manager.blank?%>
<%count2 = 0%>
<%for cnt in manager%>
<%count2 +=cnt.subordinates.size  %>
<%end%><%end%>
<%count = count1 + count2%>
 <div  align="left",  id ="<%emp.name%>">
<%= image_tag("plus-button-green.png",:class => "plus",:id=> "#{emp.name}_plus", size: "20x20", onclick: "checksub('#{emp.name}','plus')".html_safe)%>
<%= image_tag("minus.jpeg", :class => "minus", :id => "#{emp.name}_minus" ,size: "20x20", onclick: "checksub('#{emp.name}','minus')".html_safe)%>
<a href="javascript:onclick=show_employee(<%= emp.id%>)" class="high" >
<%= emp.name+'('+count.to_s+')'%></a>

<br /><br />

</div> 
<%@sub = emp.subordinates%>
<%if !@sub.blank?%>
<div id = "<%= emp.name%>" style ="display:none;">
<%for sub in @sub%>
 
  

<a href="javascript:onclick=show_employee(<%= sub.id%>)" class="blue">

<%= sub.name+'('+count2.to_s+')'%></a>
<%#= link_to 'Show', sub %>
<br />

<%@level3 = sub.subordinates %>
<%if !@level3.blank?%>
<div >
<%for level3 in @level3%>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<a href="javascript:onclick=show_employee(<%= level3.id%>)" class="level">

<%= level3.name%></a>
<br />
<%end%>
</div>
<%end%>
<%end%>
</div>
<%end%>
<%end%>

</div>
<div id= 'showing_employee' class ="col-sm-6" style ="display:none;" ></div>
<script>
	$('.minus').hide();
	function checksub(x,y){
var res =  new String(x);
if (y == 'plus'){
	$('#'+res+'_plus').hide();
  	$('#'+res+'_minus').show();
$('#'+res).show();
    
}
else{
$('#'+res+'_plus').show();
$('#'+res+'_minus').hide();
$('#'+res).hide();

}

	}


function show_employee(emp_id){
$('#showing_employee').show();
$.ajax({
        url:"/employees/"+emp_id,
         async: false,
          success: function(result){

            $('#showing_employee').html(result);

}});

}

</script>