applcation/config/routes.rb
Rails.application.routes.draw do
  resources :dash_boards
  resources :employees
  resources :books
 devise_for :users, controllers: { sessions: 'users/sessions' } # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 get 'search_employees' => 'employees#search_employee'
 get 'users/signout' 
 get 'load_link_details' => 'dash_boards#load_link_details'
 get 'check_link_details' => 'dash_boards#check_link_details' 
 get 'check_employee_type' => 'employees#check_employee_type'
 get 'organization_chart' => 'dash_boards#show_organization_chart'
 get 'emp_list_show' => 'employees#emp_list_show'
 get 'employeelogincreate' => 'employees#login_page'
 post 'employees/create_credentials' =>'employees#create_credentials'
# get 'search_employees' => 'employees#search_employee'
 root to: "dash_boards#index"
get 'dep_create'=>'departments#new'
 post 'departments/create' => 'departments#create'
end

applcation/app/models/employee.rb
class Employee < ApplicationRecord
	resourcify
	belongs_to :user, :optional => true
has_many :subordinates, class_name: "Employee",
                          foreign_key: "parent_id"
 
  #belongs_to :parent, class_name: "Employee"
mount_uploader :image_url, ImageUploader

end

applcation/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
 load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_url, alert: exception.message
end



  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  render :layout => false
  end
  def persnal
  end

def department_creation
end

  # GET /employees/new
  def new
@employee = Employee.new

if params[:from] == 'start'
render :layout => false
end
  end
  def login_page
@user_emp = User.all.collect{|a| a.emp_code}
 @emp_emp = Employee.all.collect{|e| e.emp_code}
 @res = @user_emp - @emp_emp 
  if params[:from] != "login_credentials"

render :layout => false
end

end
def create_credentials
@exist = User.find_by_email(params[:email])
if !@exist
@user = User.new
@user.email = params[:email]
@user.password = params[:password]
@user.password = params[:password_confirmation]
@user.department_id= params[:department][:id]
dep = Department.find(params[:department][:id].to_i).dep_code
@dep = User.where("emp_code LIKE ? and department_id=?", "%#{dep}%",params[:department][:id].to_i).last
if (@dep && @dep.department_id.to_i == params[:department][:id].to_i)
  num = @dep.emp_code.index('_')
val = @dep.emp_code[num.to_i+1..-1].to_i + 1
code = 'BES'+'_'+dep+ '_'+val.to_s
@user.emp_code = code  
else
code = 'BES'+'_'+dep+ '_'+1.to_s
@user.emp_code = code  
  end
status = false
  User.transaction do
status = @user.save
@role = Role.find_by_id(params[:emp][:role].to_i).name
if status
if @role=="employee"
status = @user.add_role(:employee)
elsif @role=="hr"
status=@user.add_role(:hr)
elsif @role=="manager"
status =@user.add_role(:manager)
elsif @role == "admin"
status =@user.add_role(:admin)
end
end
end
if status
flash[:notice] =  "successfully created"
  redirect_to :action=> 'login_page',:from=> 'login_credentials'
else
flash[:notice] =  "unsuccesfull"
  redirect_to :action=> 'login_page', :from=> 'login_credentials'
end
else
flash[:notice] =  "email already exist"
  redirect_to :action=> 'login_page', :from=> 'login_credentials'

end
end

  # GET /employees/1/edit
  def edit
  
  end
  def emp_list_show
if params[:from] == "search"
@emp_list = Employee.where("name ilike ?", "%#{params[:name]}%")
#raise @emp_list.inspect
end

render :layout=> false
  end
def search_employee
render :layout=> false
end

def check_employee_type
if !params[:paras].blank?
str = params[:paras].to_s.split('_')
dep = Department.find_by_dep_code(str[1])
if params[:type] == "Employee"
#raise gjh.inspect
@employee_typ =Employee.joins(:user).where("users.department_id =? and employees.level = ?",dep.blank? ? nil :dep.id.to_i,"Manager")
elsif params[:type] == "Manager"
@employee_typ = Employee.where("level = ?","CEO")
end


elsif params[:type] == "Employee"
#raise gjh.inspect
@employee_typ =Employee.where(" employees.level = ?","Manager")
elsif params[:type] == "Manager"
@employee_typ = Employee.where("level = ?","CEO")
end
render :layout => false
end
  # POST /employees
  # POST /employees.json
def create
raise params.inspect 
    @employee = Employee.new(employee_params)
    @employee.date = params[:employees]["written_on(3i)"] 
    @employee.month = params[:employees]["written_on(2i)"] 
    @employee.year = params[:employees]["written_on(1i)"] 
    @employee.level = params[:employee][:level] 
    @employee.parent_id = params[:employee][:parent_id].to_i if !params[:employee][:parent_id].blank?
    @employee.user_id = current_user.id
    
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name,:designation,:image_url,:addres,:address1,:city,:region,:postal_code,:aadhar,:pan,:phone,:blood,:marital,:emp_code)
    end
end

applcation/app/helpers/employees_helper.rb
module EmployeesHelper
end

applcation/app/views/employees/_form.html.erb
<script type="text/javascript" data-turbolinks-eval=false>
</script>
<%= form_for @employee do |form| %>

  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>

  <legend><b><%= ("Company Information")%></b></legend>
  <table align='center' class="tablecss" cellspacing=0 cellpadding=5 align=center width="100%" >
<tr>
  <td colspan = "1"><%= form.label :'Employee code' %></td>
  <td colspan = "1"><%= form.text_field :emp_code, :value => params[:emp_code],:readonly => true %></td>
</tr>

<tr>
  <td colspan = "1"><%= form.label :Name %></td>
  <td colspan = "1"><%= form.text_field :name %></td>
</tr>
<tr>
 <td colspan = "1"><%= form.label :Designation %></td>
 <td colspan = "1"><%= form.text_field :designation %></td>
</tr>

<tr>
  <td colspan = "1"><%= form.label "Employee Type" %></td>
  <td colspan = "1"> <%= form.select :level, ["Employee", "Manager", "CEO"], :prompt=> "select type" %></td>
</tr>
<tr id ='report'>
  
<tr>
  <td colspan = "1"><%= form.label :Image %></td>
  <td colspan = "1"><%= form.file_field :image_url %></td>
</tr>
<tr>
  <td colspan = "1"><%= form.label :'Address for Communication' %></td>
  <td colspan = "1"><%= form.text_area :addres %></td>
</tr>
<tr>
  <td colspan = "1"><%= form.label :Dob %></td>
  <td colspan = "1"><%= date_select("employees", "written_on",start_year: 1985, order: [:day, :month, :year]) %></td>
</tr>

</tr>


</table>
</fieldset>





<fieldset>
<legend><b><%= ("Personal Information")%></b></legend>
<table align='center' class="tablecss" cellspacing=0 cellpadding=5 align=center width="100%" >
  <tr>
 <td colspan = "1"><%= form.label :Permanent_Addres %></td>
 <td colspan = "1"><%= form.text_field :address1 %></td>
</tr>
  <tr>
  <td colspan = "1"><%= form.label :City %></td>
  <td colspan = "1"><%= form.text_field :city %></td>
</tr>
<tr>
 <td colspan = "1"><%= form.label :Postal_code %></td>
 <td colspan = "1"><%= form.text_field :postal_code %></td>
</tr>
<tr>
  <td colspan = "1"><%= form.label :Region %></td>
  <td colspan = "1"><%= form.text_field :region %></td>
</tr>

<tr>
 <td colspan = "1"><%= form.label :Aadhar_no %></td>
 <td colspan = "1"><%= form.text_field :aadhar %></td>
</tr>
 <tr>
  <td colspan = "1"><%= form.label :Pan_no %></td>
  <td colspan = "1"><%= form.text_field :pan %></td>
</tr>

 <tr>
 <td colspan = "1"><%= form.label :Phone_no %></td>
 <td colspan = "1"><%= form.text_field :phone %></td>
</tr>
<tr>
 <td colspan = "1"><%= form.label :Blood_group %></td>
 <td colspan = "1"><%= form.text_field :blood %></td>
</tr>
<tr>
 <td colspan = "1"><%= form.label :'Marital status' %></td>
 <td colspan = "1"><%= form.text_field :marital %></td>
</tr>
 

<tr>
  
</tr>
 </table>

</fieldset>



<div align = 'center'>
       <%=submit_tag "Save",{:controller => 'employee', :action => 'create',:id=>'submit_data',:class=>"buttons"}%>
  </div>

<% end %>
<script type="text/javascript">
  $('#action').show();
</script>



<script type="text/javascript" data-turbolinks-eval=false>
  $('#action').hide();
 function clickme(data1,data2){
     
   }

$('#report').hide();
$('#employee_level').change(function(){
var selectedText = $(this).find("option:selected").text();
if (selectedText == "CEO"){
$('#report').hide();

}
else{
  alert(34534);
var pars ="<%= params[:emp_code].blank? ?  '' : "#{params[:emp_code]}"%>";
alert(pars);
$.ajax({
        url:"/check_employee_type?type="+selectedText+'&paras='+pars,
         async: false,
          success: function(result){
$('#report').show();


$('#report').html(result);
}});
}
});




</script>

applcation/app/views/employees/_link_page.html.erb
<form id="secondform" target="iframe2">

<%= form_for @employee do |form| %>

  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
<fieldset>
<legend><b><%= ("Personal Information")%></b></legend>
<table align='center' class="tablecss" cellspacing=0 cellpadding=5 align=center width="100%" >
  <tr>
 <td colspan = "1"><%= form.label :Permanent_Addres %></td>
 <td colspan = "1"><%= form.text_field :address1 %></td>
</tr>
  <tr>
  <td colspan = "1"><%= form.label :City %></td>
  <td colspan = "1"><%= form.text_field :city %></td>
</tr>
<tr>
 <td colspan = "1"><%= form.label :Postal_code %></td>
 <td colspan = "1"><%= form.text_field :postal_code %></td>
</tr>
<tr>
  <td colspan = "1"><%= form.label :Region %></td>
  <td colspan = "1"><%= form.text_field :region %></td>
</tr>

<tr>
 <td colspan = "1"><%= form.label :Aadhar_no %></td>
 <td colspan = "1"><%= form.text_field :aadhar %></td>
</tr>
 <tr>
  <td colspan = "1"><%= form.label :Pan_no %></td>
  <td colspan = "1"><%= form.text_field :pan %></td>
</tr>

 <tr>
 <td colspan = "1"><%= form.label :Phone_no %></td>
 <td colspan = "1"><%= form.text_field :phone %></td>
</tr>
<tr>
 <td colspan = "1"><%= form.label :Blood_group %></td>
 <td colspan = "1"><%= form.text_field :blood %></td>
</tr>
<tr>
 <td colspan = "1"><%= form.label :'Marital status' %></td>
 <td colspan = "1"><%= form.text_field :marital %></td>
</tr>
 

<tr>
  <td colspan = "2" class="actions" id ="action" >
    <center><button onclick="submitForms()"><%=  form.submit'save' %></button></center>
</td>
</tr>
 </table>

</fieldset>


<%end%>

</form>
<iframe name="iframe1" style="display:none"></iframe>
<script type="text/javascript">
  $('#action').show();
</script>>

applcation/app/views/employees/_link_page1.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
 <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">Company Information</a></li>
        <li><a href="#tab2" data-toggle="tab">Personal Information</a></li>
        <li><a href="#tab3" data-toggle="tab">Blank</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="tab1">
          <p><%= render 'form', employee: @employee %></p>
        </div>
        <div class="tab-pane" id="tab2">
          <p><%= render 'form', employee: @employee %></p>
          

        </div>
        <div class="tab-pane disable" id="tab3">
          <p>Now I'm Blank Please Fill ME.............. .</p>
        </div>
      </div>
    </div>

  

</body>


<script language="javascript">
function submitForms{
  alert(8679);
  document.getElementById("firstform").submit();
  document.getElementById("secondform").submit();
 }
</script>
</html>

applcation/app/views/employees/check_employee_type.html.erb
<script type="text/javascript" data-turbolinks-eval=false>
</script>
<td colspan = "1"><b><%=  "To Report" %></td>
<%if @employee_typ.blank?%>

  <td colspan = "1"><%= collection_select(:employee,:name, Employee.all,:id,:name) %></td>
<%else%>
  <td colspan = "1"><%= collection_select(:employee, :parent_id, @employee_typ, :id, :name) %></td>
<%end%>

applcation/app/views/employees/department_creation.html.erb
<%= jgjgjgjkgjgjg%>
<h>hgjhsdgh</h>

applcation/app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> 
<%#= link_to 'Back', employees_path %>

applcation/app/views/employees/emp_list_show.html.erb
<style>
.backgroundGradient {
        background: linear-gradient(to bottom, white, #008080);
        color: white;
    }
tr:nth-child(even) {background-color: #A9A9A9;}
tr:nth-child(odd) {background-color: #DCDCDC;}

</style>
<%if !@emp_list.blank?%>
<table border="4px" >
<%for emp in @emp_list %>
<tr><td width="20%" ><%= image_tag "#{emp.image_url}", {:style=>"width:40%; height:40%;"}%>
	</td><td>
<%= emp.name%>
</td><td>
 <%= link_to 'Show', emp %></td><td>
<%if ( current_user.has_role?(:admin) || current_user.has_role?(:hr))%> 
<%= link_to 'Edit', edit_employee_path(emp) %><%end%></td>
</tr>
<%end%>
</table>
<%end%>

applcation/app/views/employees/index.html.erb
<style>

.style_image {
  border-right: 1px solid #000;
  width: 80px;
  height: 100px;
}
</style>

<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= image_tag employee.image_url.to_s, :class => "style_image"%></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

applcation/app/views/employees/login_page.html.erb
<p id="notice"><%= notice %></p>

<div>
<%= form_with url:  employees_create_credentials_path do |f|  %>

<table>
<tr><h2>Employee Login creation</h2>
</tr>
  <tr>
  <div class="field">
     <td width='30%'><%= "Email:" %></td>
    <td><%= text_field_tag :email %></td>  
  </div>
</tr><tr>
  <div class="field">
     <td width='30%'><%= "Password:" %></td>
  
<td>    <%= password_field_tag :password%>
     </td>
  </div></tr>
  <tr>

  <div class="field">
     <td width='30%'><%="Password confirmation:" %></td>
    <td><%= password_field_tag :password_confirmation %></td><br />
  </div></tr>
<tr>
  <div class="field">
     <td width='30%'><%="Department:" %></td>
    <td><%= collection_select(:department, :id, Department.all, :id, :dep_name) %></td><br />
  </div></tr>

<tr >


<tr>
  <div class="field">
     <td width='30%'><%="Role:" %></td>
    <td><%= collection_select(:emp, :role, Role.all, :id, :name, {:selected=>Role.find_by_name('Employee')}) %></td><br />
  </div></tr>

<tr >
  <div class="actions">
     
     <td width='30%' ></td><td><%= submit_tag "Create Credentails", :id=> 'login_emp', style: 'width:40%;background-color:#0066A2;color:white;    border-radius: 10px 10px 10px 10px;border-style: outset;'%></td>
  </div></tr>
<% end %>
</div>
<div>

<%if !@res.blank?%>
<table style="border:3px solid black">
<%for res in @res%>
<tr><td>
<%= link_to res, new_employee_path(:emp_code => res), :"data-turbolinks" => false%></td></tr>
<%end%>
</table>
<%end%>

</div>


<script>
$('#login_emp').click(function (event){

if ($('#email').val() == ""){

  alert('give email');
    event.preventDefault();
}
if ($('#password').val() == ""){

  alert('give password');
    event.preventDefault();
}
if ($('#password_confirmation').val() == ""){

  alert('give password_confirmation');
    event.preventDefault();
}
if ($('#password').val() != $('#password_confirmation').val()){

  alert('give same passwords');
    event.preventDefault();
}

});

  </script>

applcation/app/views/employees/new.html.erb
<!DOCTYPE html>
<html>
<head>

<style>
h1 { 
    display: block;
    font-size: 2em;
    margin-top: 0.67em;
    margin-bottom: 0.67em;
    margin-left: auto;
    margin-right: auto;
    font-weight: bold;
    color: #006400;
    
}
table td{
    border: 1px solid black;
   width: 1005px;
  }
  body { 
    display: block;
    margin: 4px;
}
body:focus { 
    outline: none;
 
</style>
</head>
<body align ='center'>
<h5><center>New Employee</center></h5>
  <table align='center' class="tablecss" cellspacing=0 cellpadding=5 align=center width="100%" >
<tr><td>
<%= render 'link_page1', employee: @employee %>

</td></tr>
<tr><td>
<%= link_to 'Back', dash_boards_path %>
</td></tr>
</td></tr></table>
</body>
</html>

applcation/app/views/employees/persnal.html.erb
<h>hiiiiii</h>

applcation/app/views/employees/search_employee.html.erb
<style>
.spacer {
    background-color: tomato;
    margin: 20px 5px;
}
.same{
	margin-left: 200px;
    margin-right: 200px;
    }

</style>
	<div   class="same"  align="center" >

<h4>   Enter Employee Name:<h4> 

<div class="input-group">
<input type="text" label="Employee name" class="form-control"  width="20%"  placeholder="Search Employee" name="search">
    <div class="input-group-btn"> 
       <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
 </div> 
    </div>

	</div>
<div id= "list" style="display:none;" align="center">
<br/><br/>
</div>
<script>
$('.btn').click(function(){

var name = $('input:text[name=search]').val();
$.ajax({
        url:"/emp_list_show?from="+'search'+'&name='+name,
         async: false,
          success: function(result){
          	
            $('#list').show();
            $('#list').html(result);
}});


});

</script>

applcation/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @employee.designation %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag(@employee.image_url.to_s) %>
</p>

<p>
  <strong>Addres to Communicate:</strong>
  <%= @employee.addres %>
</p>
<p>
  <strong>Date of Birth:</strong>
  <%= "#{@employee.date}/#{@employee.month}/#{@employee.year}" %>
</p>
<%if ( current_user.has_role?(:admin) || current_user.has_role?(:hr))%>
<%= link_to 'Edit', edit_employee_path(@employee) %> <%#= link_to 'Back', employees_path %>
<%end%>
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======

<%#= link_to 'Back', employees_path %>
</html>

>>>>>>> 3cdb48fd7ef53dd6650e47161c450830e5109e20
>>>>>>> bd04555e925d0dc33117c14cf3292d3ed8c70452